# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addBook.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_addBook(object):
    def setupUi(self, Ui_addBook):
        Ui_addBook.setObjectName("Ui_addBook")
        Ui_addBook.resize(338, 140)
        self.centralwidget = QtWidgets.QWidget(Ui_addBook)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 318, 117))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.bookId = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookId.setFont(font)
        self.bookId.setObjectName("bookId")
        self.horizontalLayout.addWidget(self.bookId)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.amount = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.amount.setFont(font)
        self.amount.setObjectName("amount")
        self.horizontalLayout_2.addWidget(self.amount)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.bookTitle = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookTitle.setFont(font)
        self.bookTitle.setObjectName("bookTitle")
        self.horizontalLayout_3.addWidget(self.bookTitle)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.bookAuthor = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bookAuthor.setFont(font)
        self.bookAuthor.setObjectName("bookAuthor")
        self.horizontalLayout_4.addWidget(self.bookAuthor)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.b_add = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b_add.setFont(font)
        self.b_add.setObjectName("b_add")
        self.verticalLayout.addWidget(self.b_add)
        Ui_addBook.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Ui_addBook)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 338, 22))
        self.menubar.setObjectName("menubar")
        Ui_addBook.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Ui_addBook)
        self.statusbar.setObjectName("statusbar")
        Ui_addBook.setStatusBar(self.statusbar)

        self.retranslateUi(Ui_addBook)
        QtCore.QMetaObject.connectSlotsByName(Ui_addBook)

    def retranslateUi(self, Ui_addBook):
        _translate = QtCore.QCoreApplication.translate
        Ui_addBook.setWindowTitle(_translate("Ui_addBook", "Thêm sách"))
        self.label.setText(_translate("Ui_addBook", "Sách ID:"))
        self.label_2.setText(_translate("Ui_addBook", "Số Lượng: "))
        self.label_3.setText(_translate("Ui_addBook", "Tiêu đề: "))
        self.label_4.setText(_translate("Ui_addBook", "Tác giả: "))
        self.b_add.setText(_translate("Ui_addBook", "Thêm"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_addBook = QtWidgets.QMainWindow()
    ui = Ui_Ui_addBook()
    ui.setupUi(Ui_addBook)
    Ui_addBook.show()
    sys.exit(app.exec_())
